### ISSUE TITLE
Add file link to capture templates

### ISSUE THREAD

**Issue by patgro1** [kristijanhusak/orgmode.nvim#10]
**Does this feature exist in Emacs orgmode?**
* [x] Yes
* [ ] No

**If answer to first question is "Yes", please provide the link to the orgmode manual or any documentation related to the feature**

https://orgmode.org/guide/Capture.html

> * TODO
>   [[file:LINK TO WHERE YOU INITIATED CAPTURE]]
>

**Comment by kristijanhusak** [comment]
Added it, check https://github.com/kristijanhusak/orgmode.nvim/blob/master/DOCS.md#org_agenda_templates section.

**Comment by patgro1** [comment]
Thank you very much!
