### ISSUE TITLE
Folding and coloring issues

### ISSUE THREAD

**Issue by gerazov** [kristijanhusak/orgmode.nvim#102]
### Are you using "tree-sitter" branch?

Yes

### Describe the bug

There's something fishy that happens but didn't bother posting.

These things happen on both branches but let's focus on tree-sitter :slightly_smiling_face: 

For example when first opening vim and an org file I get good coloring:

![image](https://user-images.githubusercontent.com/15214418/136930522-11082cc2-57af-407a-a2a1-6ab6bd6fe4dc.png)

But `<Tab>` folding on the tasks doesn't work - e.g. task 1 gives error:
```vim
E5108: Error executing lua [string ":lua"]:1: Vim(normal):E490: No fold found
```
Also `<S-Tab>` cycles through the views in the messages, but no folding actually happens.

If I reload the config (`init.vim`), the text is now parsed but wrongly colored:

![image](https://user-images.githubusercontent.com/15214418/136931087-d6da1030-a11b-435a-84a3-76893f10b9bc.png)

Folding still doesn't work, but now `<S-Tab>` does work.

![image](https://user-images.githubusercontent.com/15214418/136931175-4cd2bc8a-f720-4322-8cfd-ef903e132de0.png)

And after cycling views, now folding with `<Tab>` actually works as expected :sweat_smile: 

![image](https://user-images.githubusercontent.com/15214418/136931296-8eb33564-31ae-49c6-8e39-f9244f8489e9.png)

It might be some config thing ...

### Steps to reproduce

Open an `org` file and follow the above.

### Expected behavior

1. folding should work on first opening the file
2. reloading the Vim config shouldn't mess with the coloring

### OS / Distro

Manjaro Linux

### Neovim version/commit

0.5

**Comment by kristijanhusak** [comment]
Reloading your config will not do anything regarding the folding.
If you want to recalculate folds press `zx` (see `:help zx`).
On which line it returns this message?

**Comment by gerazov** [comment]
Maybe I have something in the config that breaks it ...
`zx` doesn't help.
Folding doesn't work on any heading level.

**Comment by kristijanhusak** [comment]
Your `foldexpr` is not correct. I see that you are using `vim-polyglot` which uses https://github.com/axvr/org.vim for syntax and folding. You need to disable this plugin in polyglot:
```vim
let g:polyglot_disabled = ['org']
```
