### ISSUE TITLE
Date manipulation is incredibly slow in a big file

### ISSUE THREAD

**Issue by petRUShka** [kristijanhusak/orgmode.nvim#104]
### Are you using "tree-sitter" branch?

Yes

### Describe the bug

Date manipulation: `ORG_SCHEDULE` (c) or `ORG_TIMESTAMP_UP` (`<C-a>`) are incredibly slow inside a file with for example 3000 lines.

### Steps to reproduce

1. Create file with 3000 lines of `** TODO HEADING`
2. Try to add schedule date (`<Leader>ois`)
3. Try to increase date (`<C-a>`)
4. Witness how slow these operations are.

### Expected behavior

Be at least as fast as **jceb/vim-orgmode** analogs. These operations are less dependent on size of a file and much faster on the same file.

```
                                                      *orgmode-<LocalLeader>-sa*
  <LocalLeader>sa       Prompt for a date and insert a corresponding
                        timestamp.
...
                                              *orgmode-ctrl-a* or *orgmode-ctrl-x*
  CTRL-A or CTRL-X      Change the item under the cursor in a timestamp.
                        The cursor can be on a year, month, day, hour or
                        minute.  NOTE: The plugin 'speeddating' should be
                        installed for this feature.
```

P.S. It using plugin speeddating for this functionality which is quite nice modular approach.

### OS / Distro

Arch linux

### Neovim version/commit

NVIM v0.6.0-dev+462-g5fd455757

**Comment by kristijanhusak** [comment]
I'm assuming it's slower because whole buffer is re-parsed through treesitter each time there's an update, to get the most fresh state. I'll see if there's a way to improve this. Increase/Decrease of date can probably be optimized, adding schedule/deadline probably not that much.

**Comment by kristijanhusak** [comment]
I pushed some optimizations that should make this a better experience. For me it went down from ~5sec to like ~0.2sec. Let me know how it works for you.
Files over 10k with a lot of content in details can still be slow. I'll continue to optimize this, but this is what I have for now.

**Comment by petRUShka** [comment]
Thanks a lot! Now it works much better!
