### ISSUE TITLE
Folding works incorrectly

### ISSUE THREAD

**Issue by petRUShka** [kristijanhusak/orgmode.nvim#105]
### Are you using "tree-sitter" branch?

Yes

### Describe the bug

Suppose I have file with a lot of `** TODO HEADING` (all heading have same level).

![2021-10-17-193503_471x647_scrot](https://user-images.githubusercontent.com/146893/137637138-4beb1a15-9365-4e57-be46-498f6cbaaea0.png)

If I press <TAB> it folds to one line which is incorrect:

![2021-10-17-193508_482x323_scrot](https://user-images.githubusercontent.com/146893/137637143-d047559e-d5e3-44e7-be33-ce8a3c2a1e60.png)

### Steps to reproduce

1. Have file with o lot of heading of the same level
2. Close folds
3. Witness one line instead of several

### Expected behavior

Don't fold to just one line which is incorrect

### OS / Distro

Arch Linux

### Neovim version/commit

v0.6.0-dev+462-g5fd455757

**Comment by kristijanhusak** [comment]
Related issue: https://github.com/kristijanhusak/orgmode.nvim/issues/102

**Comment by kristijanhusak** [comment]
This should be fixed now. Please give it a test.

**Comment by petRUShka** [comment]
Unfortunately now it works as in first comment :(

![2021-10-17-193508_482x323_scrot](https://user-images.githubusercontent.com/146893/137637143-d047559e-d5e3-44e7-be33-ce8a3c2a1e60.png)

**Comment by petRUShka** [comment]
Actually on any attempt to fold. After update the plugin I don't have folds at all.

**Comment by petRUShka** [comment]
Could you please try following:
1. Download `vimrc_minimal` from https://github.com/kristijanhusak/orgmode.nvim/issues/48#issuecomment-942682844 ; correct paths, plugin manager and etc.
2. Run `nvim -u vimrc_minimal` and update plugins (`:PlugUpdate`). It also updates `nvim-treesitter `
3. Try folding with [test4.org](https://gist.github.com/8f530a48af7fc6ec06af0d13bfa36a72)

**Comment by petRUShka** [comment]
Suppose I have file:

```org
** TODO Heading
- 1
- 2
- 3
- 4
** TODO Heading

** TODO Heading
1
2
3
4
5


```

When I open it with `nvim -u vimrc_minimal test.org` it folds everything to one line.

![2021-10-30-105225_396x53_scrot](https://user-images.githubusercontent.com/146893/139525068-4acca249-48d0-40f9-a9a3-cec24ad928d8.png)

Which is incorrect.

**Comment by kristijanhusak** [comment]
@petRUShka does it set up once you do `zx`?

**Comment by levouh** [comment]
Also don't you have to specify `--noplugin` when doing a "no external config" test? Can you try with `nvim -u /path/to/minimal_init.lua --noplugin` and see if that helps? 

I was having fold issues as well, and removing `vim-polygot` solved it. It loads a handful of different things for `org` files and still breaks things even when `org` (and other "defaults" like `sensible` are disabled).

**Comment by kristijanhusak** [comment]
@levouh actually I reproduced it.

@petRUShka this cannot be fixed. You are using level 2 headings on top level. You should be using level 1 headings on top level if you don't want this to happen. If you would have all these 3 headings as level 1, this would not happen.
I properly set start of the fold on headline with `>2` and properly set `<2` on the last item in the subtree (see `:help fold-expr`). When `foldlevel` is set to 0, this is just how Neovim sets it up. It probably reads all as they are same level because their level number is same. Level 1 for some reason works perfectly fine.

**Comment by petRUShka** [comment]
@kristijanhusak, thanks. It seems that folding still works unstable (and less stable than vim-orgmode folding on the same file and actions).

Suppose we have `test.org` file:

```org
* Tasks
** TODO Heading
- 1
- 2
- 3
- 4
** TODO DDD
   CLOSED: [2021-10-31 Sun 00:32]
   dadasdadasdadadadasdadksadjadjakdjalkdjaldjalajd
   dadasdadasdadadadasdadksadjadjakdjalkdjaldjalajd
   dadasdadasdadadadasdadksadjadjakdjalkdjaldjalajd
   dadasdadasdadadadasdadksadjadjakdjalkdjaldjalajd
   dadasdadasdadadadasdadksadjadjakdjalkdjaldjalajd
   (dadasdadasdadadadasdadksadjadjakdjalkdjaldjalajd)
** TODO Heading

  da
  da
* Level 1
** TODO Heading
1
2
3
4
5
```

Open this file and then:
```
7gg
dar
zx
zc
```

After this chain of commands you see wrong folding:

![2021-10-31-003627_325x112_scrot](https://user-images.githubusercontent.com/146893/139559050-843f4e6d-32d9-467c-9340-9bfb2892c701.png)

**Comment by kristijanhusak** [comment]
@petRUShka does it happen if you write the file after `dar`?

**Comment by petRUShka** [comment]
Yes, after `:w` folding remains the same

**Comment by kristijanhusak** [comment]
@petRUShka I pushed a change that makes sure that current buffer is always up to date. That should fix the issue.

**Comment by petRUShka** [comment]
It seems like folding is working good!
