### ISSUE TITLE
Error opening help

### ISSUE THREAD

**Issue by jamesob** [kristijanhusak/orgmode.nvim#11]
**Describe the bug**
The help functionality fails with a lua error on my system with `Invalid key 'border'`.

**To Reproduce**
1. Open an org buffer
2. Hit `?` to open help

**Screenshots**
![tmp](https://user-images.githubusercontent.com/73197/123830465-4e65f000-d8d1-11eb-8e78-047312730fb1.png)

**System information:**
```
 % nvim --version
NVIM v0.5.0-856-g7dfeadb0f
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/lib/ccache/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/james/src/neovim/build/config -I/home/james/src/neovim/src -I/home/james/src/neovim/.deps/usr/include -I/usr/include -I/home/james/src/neovim/build/src/nvim/auto -I/home/james/src/neovim/build/include
Compiled by james@slug

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/james/.local/share/nvim"

Run :checkhealth for more info
```

**Comment by kristijanhusak** [comment]
Do you have latest neovim? Seems  like you have the older version which does not support borders.

**Comment by jamesob** [comment]
Good point, thanks for the help. I'll try upgrading. If that's indeed the case is there some way we could build in a warning conditional on neovim version?

**Comment by kristijanhusak** [comment]
I don't think there's a way to check that. V0.5 that is officially being released on Friday will have it, so I don't think we should bother about this.

**Comment by jamesob** [comment]
FWIW here's how you might do such a check: https://vi.stackexchange.com/a/9942

**Comment by kristijanhusak** [comment]
> FWIW here's how you might do such a check: [vi.stackexchange.com/a/9942](https://vi.stackexchange.com/a/9942)

Thanks, but I still think it's not worth it.
