### ISSUE TITLE
How to open agenda in other file(not org file)

### ISSUE THREAD

**Issue by Leiyi548** [kristijanhusak/orgmode.nvim#119]

**Comment by Leiyi548** [comment]
@kristijanhusak I'm sorry. I'm a novice at org. I try to learn org mode here, but I find it difficult to learn. I misunderstand the concept of agenda. I think defining an agenda can be opened in any file and anywhere. I urgently need someone to use orgmode.nvim blog or YouTube

**Comment by kristijanhusak** [comment]
Try checking this: https://www.youtube.com/watch?v=nsv33iOnH34
