### ISSUE TITLE
Cant find in help documentation how to change language for calendar and dates

### ISSUE THREAD

**Issue by benignoc** [kristijanhusak/orgmode.nvim#120]
### Are you using "tree-sitter" branch?

Yes

### Describe the bug

Thank you for the plugin.

I have not been able to find out how to change language local used for inserted dates (such as scheduled etc: <mapleader>ios)  or in the calendar view. 

  1 Week-agenda (W43):
  2 lunes      25 octubre 2021
  3 martes     26 octubre 2021
  4 miércoles 27 octubre 2021
  5 jueves     28 octubre 2021
  6 viernes    29 octubre 2021                                                                                                                                                                 
  7 sábado    30 octubre 2021
  8 domingo    31 octubre 2021

SCHEDULED: <2021-11-02 mar 09:00>

I am get the days etc in Spanish, and I am not entirely sure where to look at to change this setting. It may well be related to another dependant plugin or even neovim config ?.

Thank you,
Benigno.

### Steps to reproduce

1. Going into Calendar view <mapleader>oa a
2. Or inserting scheduled date <mapleader>ios

### Expected behavior

I guess its possible to change the locals used, but I am at a loss to find out where.

### OS / Distro

Ubuntu 20.04

### Neovim version/commit

NVIM v0.6.0-dev Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-yTy4t9/neovim-0.6.0~ubuntu1+git202110281225-d918759de-adeb5640f=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-yTy4t9/neovim-0.6.0~ubuntu1+git202110281225-d918759de-adeb5640f/build/config -I/build/neovim-yTy4t9/neovim-0.6.0~ubuntu1+git202110281225-d918759de-adeb5640f/src -I/build/neovim-yTy4t9/neovim-0.6.0~ubuntu1+git202110281225-d918759de-adeb5640f/.deps/usr/include -I/usr/include -I/build/neovim-yTy4t9/neovim-0.6.0~ubuntu1+git202110281225-d918759de-adeb5640f/build/src/nvim/auto -I/build/neovim-yTy4t9/neovim-0.6.0~ubuntu1+git202110281225-d918759de-adeb5640f/build/include Compiled by buildd@lgw01-amd64-033  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

**Comment by benignoc** [comment]
Thank you Kristijan,

    So I get the agenda in Spanish, I check language just by :language, and I get this list:
Current language: "LC_CTYPE=en_US.UTF-8;LC_NUMERIC=C;LC_TIME=es_ES.UTF-8;LC_COLLATE=en_US.UTF-
8;LC_MONETARY=es_ES.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=es_ES.UTF-8;LC_NAME=es_ES.UTF-8;LC_
ADDRESS=es_ES.UTF-8;LC_TELEPHONE=es_ES.UTF-8;LC_MEASUREMENT=es_ES.UTF-8;LC_IDENTIFICATION=es_E
S.UTF-8"

Then I do :language en_US.utf8 and when I do the agenda, it appears in correctly in english.

So I am not sure why it did not show them in English to start with, but I guess it solves the issue.

thanks a lot,
Benigno.

**Comment by kristijanhusak** [comment]
Ok, then just add `language en_US.utf8` to your init.vim and everything should work fine. Or change the locale on the system level, since it seems it's set to `es_ES` for most of the things.

**Comment by benignoc** [comment]
Thank you very much Kristijan, this solves it.

**Comment by kristijanhusak** [comment]
Awesome! Closing then.
