### ISSUE TITLE
date increment/decrement does not take a count

### ISSUE THREAD

**Issue by crypt17** [kristijanhusak/orgmode.nvim#121]
### Does this feature exist in Emacs orgmode core?

No

### Feature value

when incrementing a date 7 days it would be handy to be able to do 7<C-a>

it appears that this can be done by changing the date:add function to the following

 ---@param opts table
---@return Date
function Date:add(opts)
  opts = opts or {}
  local date = os.date('*t', self.timestamp)
  local count = vim.v.count1
  for opt, val in pairs(opts) do
    if opt == 'week' then
      opt = 'day'
      val = val * 7
    end
    val = val * count
    date[opt] = date[opt] + val
  end
  return self:from_time_table(date)
end

**Comment by kristijanhusak** [comment]
This is now supported on "tree-sitter" branch.
