### ISSUE TITLE
orgmode_hide_emphasis_markers with tree-sitter

### ISSUE THREAD

**Issue by levouh** [kristijanhusak/orgmode.nvim#124]
### Are you using "tree-sitter" branch?

Yes

### Describe the bug

More of a question, but the idea that the feature isn't working would seemingly mean that this is a bug? Not familiar with _Treesitter_ at all, but when using syntax markers in the a file the `/.../` markers should be concealed, right? I don't see any issues 

### Steps to reproduce

1. Setup `orgmode.nvim` with `org_hide_emphasis_markers` as `true`
2. Open an `org` file
3. Type text surrounded by `/.../` markers

### Expected behavior

Markers for italic, bold, etc. are hidden.

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/31262046/139603021-f3195b85-2743-4c7a-a089-c4c8b9343bae.png)

### OS / Distro

Linux

### Neovim version/commit

NVIM v0.6.0-dev+518-g1dbbaf89b

### Additional context

Again, not sure what the expected behavior here is.

**Comment by kristijanhusak** [comment]
Are you sure it works for other things (bold, strikethrough, etc). Works fine for me:

![screenshot](https://i.imgur.com/ZEgzojO.png)

What is your `&conceallevel` ?

**Comment by kristijanhusak** [comment]
@levouh can we close this now?
