### ISSUE TITLE
Using org-timestamp-up_day blocks vim if executed not on date

### ISSUE THREAD

**Issue by gerazov** [kristijanhusak/orgmode.nvim#129]
### Are you using "tree-sitter" branch?

Yes

### Describe the bug

Vim is blocked and cannot be closed, i.e. its process must be killed.

### Steps to reproduce

Go to any place that is not a date and trigger `org-timestamp-up_day`.

### Expected behavior

Nothing should happen.

### OS / Distro

Manjaro Linux

### Neovim version/commit

0.5.1

**Comment by kristijanhusak** [comment]
Good catch. Should be fixed now.

**Comment by gerazov** [comment]
Still doesn't work on my side ...

**Comment by kristijanhusak** [comment]
Are you using custom mapping maybe?

**Comment by gerazov** [comment]
Yes:
```lua
mappings = {
    org = {
      org_timestamp_up = '+',
      org_timestamp_down = '=',
      org_timestamp_up_day = '_',
      org_timestamp_down_day = '-'
    }
  }

```

**Comment by kristijanhusak** [comment]
Ok, I didn't account for that. Should be working now.

**Comment by gerazov** [comment]
works! thanks :pray:
