### ISSUE TITLE
Use taskwarrior database format?

### ISSUE THREAD

**Issue by reportaman** [kristijanhusak/orgmode.nvim#13]
**Does this feature exist in Emacs orgmode?**
* [ ] Yes
* [X] No

Because Org-mode wasn't available for a long time in vim, I guess people use taskwarrior. If orgmode.nvim can use taskwarrior under the hood, (using [tasklib](https://github.com/robgolding/tasklib), and [taskwarrior](https://github.com/GothenburgBitFactory/taskwarrior)) then users can leverage the good side of both the worlds. For instance taskwarrior has a solid CLI interface, and web servers to sync the tasks across devices using services like https://inthe.am or https://freecinc.com.

As a sidenote, they also have a vim plugin [taskwiki](https://github.com/tools-life/taskwiki) which is to generate different kind of view in [vimwiki](https://github.com/vimwiki/vimwiki) files of tasks.

**Comment by kristijanhusak** [comment]
I don't plan to create any kind of converters/transformers/etc., but I'll gladly add it to README if someone else creates it. There's enough work to be done in orgmode itself, and this is out of scope.
