### ISSUE TITLE
Support count on ctrl-a and ctrl-x

### ISSUE THREAD

**Issue by petRUShka** [kristijanhusak/orgmode.nvim#138]
### Are you using "tree-sitter" branch?

Yes

### Describe the bug

You cannot increase\decrease date for 7 days for example.

[vim-orgmode CTRL-A CTRL-X functionality](https://github.com/jceb/vim-orgmode/blob/master/doc/orgguide.txt#L895) relies on Tim Popes [speeddating plugin](https://github.com/tpope/vim-speeddating). Quotation from its docs:

Pressing `5<C-X>` on the `03` in the first line below transforms it into the
second:

    Sat, 01 Jan 2000 00:00:03 +0000
    Fri, 31 Dec 1999 23:59:58 +0000

I suggest to depend on speeddating to make plugin more [unix-way](https://en.wikipedia.org/wiki/Unix_philosophy) or to implement count with your own implementation.

### Steps to reproduce

- Add any date
- Place cursor on any part of date (days for example)
- Run `5CTRL-A`
- See only date increased only for one day

### Expected behavior

Have support for count 

### OS / Distro

ArchLinux

### Neovim version/commit

v0.6.0-dev+462-g5fd455757

**Comment by kristijanhusak** [comment]
There's already an issue for this. https://github.com/kristijanhusak/orgmode.nvim/issues/138.

I don't plan to depend on any plugin beside treesitter. Adding count shouldn't be too complicated to the current functionality.

Closing as duplicate.

**Comment by kristijanhusak** [comment]
@petRUShka Support for this is now added on "tree-sitter" branch.

**Comment by petRUShka** [comment]
@kristijanhusak it is working very well! Thanks!
