### ISSUE TITLE
Error: using List as String

### ISSUE THREAD

**Issue by nathom** [kristijanhusak/orgmode.nvim#142]
### Describe the bug

When I open an org file with `:e`, it shows this exception before waiting for a few seconds and properly loading the file.

```
Error detected while processing FileType Autocommands for "org":
E5108: Error executing lua Vim:E730: using List as a String
Press ENTER or type command to continue
```

### Steps to reproduce

1. Run neovim
2. Open an org file with `:e test.org`.

### Expected behavior

There should be no error.

### Minimal init.lua

Error doesn't happen with `minimal_init.lua`

### OS / Distro

macOS 12

### Neovim version/commit

NVIM v0.6.0-dev+501-gcb15055c2

**Comment by kristijanhusak** [comment]
> Error doesn't happen with minimal_init.lua

Can you double check if your configuration is ok?

**Comment by nathom** [comment]
I was able to resolve this after installing and reinstalling the plugin.
