### ISSUE TITLE
Default formatexpr doesn't respect textwidth

### ISSUE THREAD

**Issue by mgoral** [kristijanhusak/orgmode.nvim#144]
### Describe the bug

Hi, I found out that after merge of treesitter branch, the default formatexpr doesn't work for me: it doesn't respect textwidth: long lines aren't automatically broken and `gq` doesn't work at all. I believe it's because of the default implementation of `OrgmodeFormatExpr()`, because once it's changed, things go back to normal.

### Steps to reproduce

1. Create `foo.org`:

```
This was a triumph. I'm making a note here: huge success. It's hard to overstate my satisfaction!
```

2. Open it with nvim -u init-min.lua foo.org
3. Make sure that echo &formatexpr returns OrgmodeFormatExpr()
3. Press gqq
4. Nothing happens

### Expected behavior

The file should change to this:

```
This was a triumph. I'm making a note here: huge success. It's hard to
overstate my satisfaction!
```

A workaround is `:set formatexpr=nvim_treesitter#formatexpr()`. Is this how it's supposed to work? If so, can this be added to the documentation?

### Minimal init.lua

```
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      {'nvim-treesitter/nvim-treesitter', run = ':TSUpdate'},
      {'kristijanhusak/orgmode.nvim', branch = 'master' },
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  }
end

_G.load_config = function()
  require('nvim-treesitter.configs').setup({
    ensure_installed = {"org"}
  })

  local parser_config = require('nvim-treesitter.parsers').get_parser_configs()

  parser_config.org = {
    install_info = {
      url = 'https://github.com/milisims/tree-sitter-org',
      revision = 'main',
      files = {'src/parser.c', 'src/scanner.cc'},
    },
    filetype = 'org',
  }
  vim.cmd[[packadd nvim-treesitter]]
  vim.cmd[[TSUpdate]]

  require('orgmode').setup()
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end

vim.opt.textwidth = 77
```

### OS / Distro

Debian Bullseye

### Neovim version/commit

0.5.0

**Comment by kristijanhusak** [comment]
I pushed small change that should fallback to internal formatting when there isn't anything to format for orgmode. Can you pull latest master and give it a change?

Where are you getting `nvim_treesitter#formatexpr()` from ? I don't think `nvim-treesitter` has that function exposed.

**Comment by kristijanhusak** [comment]
Should be fixed now. I had some errors happening in the  background that were not properly handled.

**Comment by mgoral** [comment]
Thank you, it works now! The indent isn't preserved when noindent is enabled though, but I think I can live with that. :)

Regarding `nvim_treesitter#formatexpr()`... I didn't bother to check if it exists, because it worked for my (very limited) test :) I assumed that vim will yell at me if I used not existing function. Now I see that it worked the same as `set formatexpr=`.

**Comment by kristijanhusak** [comment]
> The indent isn't preserved when noindent is enabled though
noindent basically removes any indentation that you have. This is still not well supported because of Neovim limitation for "virtual indentation".
