### ISSUE TITLE
Diagnostics change on Neovim HEAD

### ISSUE THREAD

**Issue by levouh** [kristijanhusak/orgmode.nvim#154]
### Describe the bug

```
Error detected while processing CursorHoldI Autocommands for "*.org":                                                                                                            
E5108: Error executing lua ...nvim7mLQJN/usr/share/nvim/runtime/lua/vim/diagnostic.lua:354: Vim(autocmd):E680: <buffer=0>: invalid buffer number 
stack traceback:
        [C]: in function 'cmd'
        ...nvim7mLQJN/usr/share/nvim/runtime/lua/vim/diagnostic.lua:354: in function 'schedule_display'
        ...nvim7mLQJN/usr/share/nvim/runtime/lua/vim/diagnostic.lua:1131: in function 'show'
        ...nvim7mLQJN/usr/share/nvim/runtime/lua/vim/diagnostic.lua:638: in function 'report'
        [string ":lua"]:1: in main chunk
```

### Steps to reproduce

1. Ensure on the latest _Neovim_ `HEAD`
2. Open a `.org` file
3. Let `CursorHoldI` trigger
4. Observe above error

### Expected behavior

No errors when reporting diagnostics

### Minimal init.lua

The one featured in this repo. works for it.

### OS / Distro

Linux

### Neovim version/commit

NVIM v0.6.0-dev+594-g36538417f

### Additional context

Potentially related _Neovim_ core change [here](https://github.com/neovim/neovim/pull/16323).

**Comment by levouh** [comment]
Simply changing the `diagnostic.set` call to pass the current buffer rather than `0` fixes this @kristijanhusak, just wanted to create an issue and look at it a bit more before jumping to a conclusion. The change to core is [here](https://github.com/neovim/neovim/pull/16323).

Going to try an older version (that doesn't have the above _PR_) and validate that is actually what causes the issue. Still don't see how they are 100% related yet, but will create a _PR_ here to fix the issue (hopefully in a backwards compatible way) when I have time.

**Comment by kristijanhusak** [comment]
That shouldn't be the issue. As the comment says on that PR:
> while 0 means "current buffer"

And I am passing 0 here. I'll take a look.

**Comment by kristijanhusak** [comment]
Seems like that's the issue. They are not handling it on one place. Pushed a fix.

**Comment by levouh** [comment]
Cool, will look at if after work if you don't find anything, just wanted to create an issue to track it.

**Comment by levouh** [comment]
Ahh missed you already closed it. Thanks!

**Comment by kristijanhusak** [comment]
Yeah, should be fixed. Thanks for reporting!
