### ISSUE TITLE
Diagnostics in china

### ISSUE THREAD

**Issue by Leiyi548** [kristijanhusak/orgmode.nvim#156]
![image](https://user-images.githubusercontent.com/76139422/142660915-f4167c55-3270-4335-b031-d455fdf8dc79.png)
I'm from China. I like your plug-in very much. I use your plug-in to manage my daily life, but there is a problem. If I set the schedule, it will display an error. This is a Chinese error. How can I display this schedule in Chinese

**Comment by kristijanhusak** [comment]
What does that sign mean?

**Comment by Leiyi548** [comment]
@kristijanhusak When I press < leader > OS to insert the schedule
Orgmode will diagnose errors(because have chinese)

**Comment by kristijanhusak** [comment]
@Leiyi548 are you ok with having dates in English, or any other language that's not specifically chinese?

**Comment by kristijanhusak** [comment]
@Leiyi548 to use english for dates, set different locale for Neovim like I explained here: https://github.com/kristijanhusak/orgmode.nvim/issues/120#issuecomment-954700739

**Comment by kristijanhusak** [comment]
I added small section about this to readme troubleshoot section https://github.com/kristijanhusak/orgmode.nvim#troubleshoot

**Comment by Leiyi548** [comment]
@kristijanhusak Thank you. The problem of setting me to English language has been solved
