### ISSUE TITLE
Feature request: Lazy load plugin

### ISSUE THREAD

**Issue by austinbostonberlin** [kristijanhusak/orgmode.nvim#18]
**Does this feature exist in Emacs orgmode?**
* [ ] Yes
* [ ] No
* [x] No idea

**If answer to first question is "No", elaborate on how this feature is valuable and what problem does it solve.**
This is probably a complicated ask, but is it possible to lazy load this plugin, for example with packer like this
`use {"kristijanhusak/orgmode.nvim", ft = "org"}`

The ft command I get is tricky as you set ftdetect from within the plugin. But perhaphs some otherway like a command like `orgInit()` that can be used to initialize/lazy-load?
...

**Additional context**

**Comment by akinsho** [comment]
@austinbostonberlin I believe you can do this in packer by using keys or events, e.g.
```lua
use {"kristijanhusak/orgmode.nvim", event = {"BufReadPre", "BufEnter *.org"}, keys = {"<leader>oa"}
```
FWIW though I started out down this path but if you run `PackerProfile` you'll find that `orgmode.nvim` has a vanishingly small startup time (2ms) on my mac and <1ms on my linux machine, so I believe however the plugin is structured it is already very cheap to load so lazy loading is an unnecessary optimisation for now 🤷🏾‍♂️

**Comment by kristijanhusak** [comment]
@akinsho summarized it pretty well. I was watching for the startup time to be as lowest as possible, and org files are loaded and parsed only after you initiate any of the actions (agenda, capture, BufEnter org). Initial load just sets up the config (https://github.com/kristijanhusak/orgmode.nvim/blob/master/lua/orgmode/init.lua#L49), and everything else is loaded on demand (https://github.com/kristijanhusak/orgmode.nvim/blob/master/lua/orgmode/init.lua#L19)

**Comment by ranjithshegde** [comment]
That is perfect! Because I had a lazy-load similar to what @akinsho described (except without the `keys` argument) and it somehow messed up treesitter folding for other filetypes. Strange
But since it is so fast and semi-lazy loaded by itself I wont go that route either!

**Comment by kristijanhusak** [comment]
Ok. Closing then. Thanks for reporting anyway.
