### ISSUE TITLE
Change TODO state on repeating task should maintain ordering

### ISSUE THREAD

**Issue by BlackEdder** [kristijanhusak/orgmode.nvim#22]
Currently changing the TODO state on a repeating task inserts the changed state on the second line. This means that they end up out of chronological order. Ideally the line should always be inserted just after the :END:, such that they are ordered in (descending) chronological order.

For example, below is the output of a current daily todo. As you can see the "State "DONE" from "TODO" lines are out of order. This is because currently these lines are inserted below the first line. Instead I'd suggest inserting updates below :END:, such that they stay in (descending) order. 

Alternatively you could try to insert the after the last line, which would also maintain chronological order (ascending). Personally I prefer to have the most recent things at the top, but I have noticed that in general orgmode seems to prefer to have the last edits at the bottom (i.e. when refiling/capturing things).

```
* TODO Daily habit 1
  SCHEDULE: <2021-07-05 Mon ++1d>
  :PROPERTIES:
  :LAST_REPEAT: 2021 -07-04 Sun 07:27
  :END:
- State "DONE" from "TODO" [2021-07-02 Fri 06:30]
- State "DONE" from "TODO" [2021-07-04 Fri 06:35]
- State "DONE" from "TODO" [2021-07-03 Fri 07:20]
```

**Comment by kristijanhusak** [comment]
Good catch. I checked how emacs is handling this, and it always appends after the `:END:`, so I set it up to behave the same way. That should give you proper descending order. Let me know if it works.

**Comment by BlackEdder** [comment]
Thank you, this seems to have worked.
