### ISSUE TITLE
Trying to append to an existing todo from the capture buffer throws an error

### ISSUE THREAD

**Issue by akinsho** [kristijanhusak/orgmode.nvim#27]
**Describe the bug**
When trying to append a capture to an existing todo or heading from inside the capture window, after using `<leader>or` and selecting a sub heading, an error is thrown.

```
E5108: Error executing lua ...k/packer/start/orgmode.nvim/lua/orgmode/capture/init.lua:145: attempt to index local 'item' (a nil value)
```

**To Reproduce**
1. Open the capture menu
2. Add some details to the template
3. hit `<leader>or` to move to a specific location
4. try to complete a sub heading e.g. `todo.org/some_heading` 
5. See error

**Expected behavior**
The TODO item should be saved to the specific part/location within the org document

**Emacs functionality**
I presume this is how it would work in Emacs.

**Screenshots**
![image](https://user-images.githubusercontent.com/22454918/124518278-ee45e100-dddd-11eb-86e7-57871b4e0023.png)

**System information:**
 - OS: Linux
 - Neovim version/commit: v.0.5

**Additional context**

**Comment by kristijanhusak** [comment]
Fixed, thanks.

Note that refiling from capture window to specific headline doesn't properly demote headings, I still need to work on that.
