### ISSUE TITLE
Optionally conceal orgmode syntax

### ISSUE THREAD

**Issue by akinsho** [kristijanhusak/orgmode.nvim#28]
When typing out orgmode syntax such as
```org
=verbatim=
/italic/
_underline_
```
The markup for these styles remains visible in the buffer. Perusing various emacs org mode talks and videos, I can't tell if it allows these to be hidden or not really, but I know that vim supports concealing much like Markdown syntax files conceal things like backticks etc.

Perhaps this could be done in a way user can configure, as I'm sure some users will prefer to see the text at all times and some like myself would prefer for things to be concealed.

**Does this feature exist in Emacs orgmode?**
I'm not sure

**If the answer is No, why do it?** (sorry, removed the original heading by mistake)
Essentially, I think the additional text being visible constantly creates visual noise when you scan a buffer. I think that when reading the contents of the buffer if the words are already highlighted correctly i.e. already italicised or bold etc. then you don't need to see the special characters making that happen unless you are about to edit that piece of text.

A good example of this in practice is actually reading this issue, all the markup has been hidden for ease of reading 😄 .

Thoughts?

**Comment by kristijanhusak** [comment]
There's an option for that (https://stackoverflow.com/a/10970665/1474465), so we can introduce it.

**Comment by kristijanhusak** [comment]
This is added. You can enable it with this option 
 https://github.com/kristijanhusak/orgmode.nvim/blob/master/DOCS.md#org_hide_emphasis_markers

**Comment by akinsho** [comment]
Awesome thanks again
