### ISSUE TITLE
Let enter in agenda view replace current file?

### ISSUE THREAD

**Issue by tami5** [kristijanhusak/orgmode.nvim#3]
Hey @kristijanhusak, this is more like a question regarding usability.

Would it nice if pressing enter in agenda view replaces previous split buffer if the previous buffer is org buffer.

Thanks

**Comment by kristijanhusak** [comment]
You should be able to achieve that by using `<TAB>` instead of `<CR>`.
If you want to switch those two mappings, just provide mappings config in setup:

```lua
require('orgmode').setup({
  mappings = {
    agenda = {
      org_agenda_switch_to = '<TAB>',
      org_agenda_goto = '<CR>',
    }
  }
})
```

**Comment by tami5** [comment]
NICE, that's good enough. Thanks @kristijanhusak
