### ISSUE TITLE
Error in agenda view using keywords other than TODO 

### ISSUE THREAD

**Issue by jghauser** [kristijanhusak/orgmode.nvim#33]
**Describe the bug**
When I set up other keywords with e.g. ` org_todo_keywords = {'TODO', 'WAITING', 'NEXT', '|', 'DONE', 'DELEGATED'}` and use one of those new keywards (e.g. 'WAITING') in an entry, then I get the following error message on opening the agenda:

![20210706_21h28m13s_grim](https://user-images.githubusercontent.com/10319377/124656371-a3d16c80-de90-11eb-9ca1-022628df4079.jpeg)

The list of tasks still opens, but the highlighting of keywords doesn't work as soon as the first new keyword appears. 
![20210706_21h32m41s_grim](https://user-images.githubusercontent.com/10319377/124656600-f1e67000-de90-11eb-9c5a-b413f6e5880e.jpeg)

**To Reproduce**
1. Add the above settings to orgmode.nvim setup function
2. Add an entry such as 'WAITING some task'
3. Open the agenda

**Expected behavior**
No error

**Emacs functionality**
I don't know.

**Screenshots**
see above.

**System information:**
 - OS: Arch
 - Neovim version/commit: 0.5 release

**Comment by kristijanhusak** [comment]
Adding custom colors via https://github.com/kristijanhusak/orgmode.nvim/blob/master/DOCS.md#org_todo_keyword_faces would fix the issue, but I fixed it to properly fallback to the right color. Let me know if it works.

**Comment by jghauser** [comment]
It works! Thanks!
