### ISSUE TITLE
Editing fails for non-written files

### ISSUE THREAD

**Issue by gergesh** [kristijanhusak/orgmode.nvim#34]
To replicate this:
1. `nvim file.org`
2. Insert some text `* Headline`
3. Try performing an orgmode operation (such as `>>`)

The following error popus up: `E5108: Error executing lua ...k/packer/start/orgmode.nvim/lua/orgmode/parser/files.lua:91: attempt to index local 'file' (a nil value)`

**Comment by kristijanhusak** [comment]
Fixed, thanks.
