### ISSUE TITLE
Can't open help after closing using `:q`

### ISSUE THREAD

**Issue by gergesh** [kristijanhusak/orgmode.nvim#35]
**Describe the bug**
After closing the help menu with `:q`, trying to open it again will fail.

**To Reproduce**
1. Open the help menu using `<leader>o?`
2. Close it using `:q`
3. Try opening the help menu again
4. Observe error `E5108: Error executing lua ...k/packer/start/orgmode.nvim/lua/orgmode/objects/help.lua:128: Vim:E95: Buffer with this name already exists`

**Comment by kristijanhusak** [comment]
Fixed. It was also happening for calendar popup, but now both are fixed. Thanks.
