### ISSUE TITLE
LaTeX Features (exporting, syntax highlighting, preview)

### ISSUE THREAD

**Issue by shaunsingh** [kristijanhusak/orgmode.nvim#36]
**Does this feature exist in Emacs orgmode?**
Yes 

**If answer to first question is "Yes", please provide the link to the orgmode manual or any documentation related to the feature**

https://orgmode.org/manual/Embedded-LaTeX.html
https://orgmode.org/manual/Exporting.html

...

**Additional context**
Unlike some other languages that are meant to be wrapped in `#+begin_src`, emacs/org has latex embedded directly into org mode. This integration consists of 

1. Allowing you to write equations inline using `$(equation)$`, and multi-line equations using` \begin{equation}` or `\begin{align}`
2. Highlighting inline latex
3. Exporting org into multiple file formats, most notably a `.tex` file which is used to produce a `.pdf` file 
4. Allowing you to create inline-previews of latex as .svgs 

**NOTE** Unlike emacs, neovim can't display images inline and lacks some other features. As such, you might be more interested in utilizing [pandoc](https://pandoc.org/org.html) and grip to render org. 

1. An example of this is here: 
<img width="846" alt="image" src="https://user-images.githubusercontent.com/71196912/124841370-11e26600-df5b-11eb-85e5-ce448e2bf89c.png">

Notice the \begin and $equation$ tags used to define latex. In emacs it looks like this: 

<img width="847" alt="image" src="https://user-images.githubusercontent.com/71196912/124841461-4e15c680-df5b-11eb-8150-41822234dc31.png">

2. In the above example, if I expand the previewed latex, it looks highlighted like this: 
<img width="847" alt="image" src="https://user-images.githubusercontent.com/71196912/124841500-638af080-df5b-11eb-8bb7-915d87e445d2.png">
Which is much easier to read than the white of orgmode.nvim

3. Emacs allows you to export org files into various other filetypes: 

<img width="886" alt="image" src="https://user-images.githubusercontent.com/71196912/124841551-84534600-df5b-11eb-8322-025e935270bb.png">

Notably, html, markdown, and latex to pdf, which allows you to produce nice looking pdfs. The pdf export also takes some cues from org mode for packages, used, title, author, and the ToC: 

<img width="360" alt="image" src="https://user-images.githubusercontent.com/71196912/124841698-d6946700-df5b-11eb-94f3-dc33fe7e43fd.png">

4. Previewing 

As displayed in the first screenshot of emacs, you can preview latex fragments. Although you can't display inline images in neovim like you can with emacs, you might be able to utilize an external preview, powered through a web-renderer similar to grip (grip itself doesn't support math).

**Comment by kristijanhusak** [comment]
Thanks for the detailed explanation.

To be honest, I have absolutely no experience with Latex. Any assistance on this topic is appreciated.

Is Latex in org only available between `/begin{something}` `/end{something}` or also outside of it?

Image preview is possible via https://pypi.org/project/ueberzug/ (only on X11), but I'm not even sure how would it be done.

For the publishing, I plan to support all publishing by using the emacs orgmode tools. I know https://github.com/jceb/vim-orgmode supports it so I assume it's possible.

From what I see, fastest thing that could be done is to allow "tex" highlight as part of org. Publishing will come later, and i'm not sure about the previews.

**Comment by shaunsingh** [comment]
> Any assistance on this topic is appreciated.

Sure, let me know if you need anything else. I have minimal experience making lua plugins but I can try my best. 

> Is Latex in org only available between /begin{something} /end{something} or also outside of it?

According to the org wiki, latex fragments are identified as any of the following 
1. Anything encased within `\begin` and `\end`
2. Anything within the LaTeX math delimiters (this is either `$text$` (no whitespaces allowed), `$$ text $$`, `\( text \)`, or `\[ text \]`

(a more detailed explanation can be found here: https://orgmode.org/manual/LaTeX-fragments.html#LaTeX-fragments)

> Image preview is possible via https://pypi.org/project/ueberzug/ (only on X11), but I'm not even sure how would it be done.

Looks good! I think the only possible way is to create a floating window, start a terminal, and use `ueberzug` to display the image. I use this method to display images for my startup dashboard. The only issue is that you would have to keep the preview aligned with scrolling text, and regenerate the preview multiple times (causing lag and performance drops)

> For the publishing, I plan to support all publishing by using the emacs orgmode tools. I know https://github.com/jceb/vim-orgmode supports it so I assume it's possible.

I believe the code we need is [Here](https://github.com/jceb/vim-orgmode/blob/50464f251ad9d300ad2a2265143c914b929f8b08/ftplugin/orgmode/plugins/Export.py). Its in python so we would need to translate that to lua, but the logic looks quite simple.

**Comment by kristijanhusak** [comment]
I think, for now, I could add latex highlighting for those fragments (via syntax region), and have publishing be done separately for everything.

For the image preview, do you know if there's a way to generate the image with emacs?

**Comment by shaunsingh** [comment]
You can use `org-latex-preview` to generate a preview of the latex equation under the cursor. I'm not sure once you generate a preview, how to extract it. 
 
<img width="1085" alt="Screen Shot 2021-07-09 at 1 37 32 PM" src="https://user-images.githubusercontent.com/71196912/125116551-e1b1d900-e0ba-11eb-9fd6-09a401aca1e1.png">

**Comment by kristijanhusak** [comment]
@shaunsingh I added some basic highlighting options. It's disabled by default. Check here https://github.com/kristijanhusak/orgmode.nvim/blob/master/DOCS.md#org_highlight_latex_and_related.

Let me know how it works for you.

**Comment by shaunsingh** [comment]
<img width="846" alt="image" src="https://user-images.githubusercontent.com/71196912/125180007-3e98b680-e1c3-11eb-8a39-c86370868608.png">

Seems like it isn't working on my end. I tried both the "native" and "entities" options. 

This is my config with packer: 
```lua
        use {
            'kristijanhusak/orgmode.nvim',
            ft = {'org'},
            config = function()
                require("orgmode").setup(
                    {
                        org_highlight_latex_and_related = 'entities'
                    }
                )
            end
        }
```

**Comment by kristijanhusak** [comment]
Please pull latest master and give it another try.
If it doesn't work, please try without packer's lazy loading.

**Comment by kristijanhusak** [comment]
I added exporting. See https://github.com/kristijanhusak/orgmode.nvim/blob/master/DOCS.md#org_export.

**Comment by shaunsingh** [comment]
> Please pull latest master and give it another try.

Thanks, works well now. 

> I added exporting.

Works as expected. Would you consider also adding `pandoc` as an export option? Might be useful for those who don't have emacs installed but would like to export to pdf.

**Comment by kristijanhusak** [comment]
Yeah, why not. I'll probably group exports to allow more options, and also expose a setting for custom exports.

**Comment by kristijanhusak** [comment]
I added pandoc exports for several file types (html, tex, pdf). Also, I added an option to add custom exports. See https://github.com/kristijanhusak/orgmode.nvim/blob/master/DOCS.md#org_custom_exports . Let me know how it works.

Regarding the preview, I'm not sure if I'll be adding it. It seems very complicated, especially since Neovim can't show images inline.

I didn't try, but you could maybe use [this solution via lsp](https://github.com/lervag/vimtex/issues/2006#issuecomment-806200204), and here's [the preview](https://github.com/lervag/vimtex/issues/2006#issuecomment-806181446).

**Comment by shaunsingh** [comment]
Is it possible by any chance to use treesitter for the latex highlighting? The treesitter colors are a little easier to read: 

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/71196912/126813277-cae76bab-c04a-4450-85f7-810e3645cf80.png">

(treesitter on the right)

**Comment by kristijanhusak** [comment]
I don't think it's possible to inject treesitter for some syntax. Once we have treesitter support in the whole org, we should be able to do this easily.

**Comment by kristijanhusak** [comment]
@shaunsingh did you had a chance to test features added through this issue? Can this be closed if everything is working as expected?

**Comment by shaunsingh** [comment]
Everything works great! The only thing I couldn't get working was the preview with lsp, since the built-in markdown renderer in my gui didn't seem to support mathjax, but that isn't something you can solve 

You can close the issue

**Comment by kristijanhusak** [comment]
Awesome, thanks for the feedback and for testing it.
