### ISSUE TITLE
Table support question

### ISSUE THREAD

**Issue by leiserfg** [kristijanhusak/orgmode.nvim#37]
Is not [vim-table-mode](https://github.com/dhruvasagar/vim-table-mode) good enough for the tables support? If it is, will it be better to advise using it or will you go for a pure Lua rewrite?

**Comment by kristijanhusak** [comment]
I wasn't even aware of that plugin, thanks! I'll give it a try and see, but for now it's definitely a way to go.

**Comment by kristijanhusak** [comment]
Added it to readme in plugins section for now, until table support is added directly in orgmode. Thanks!
