### ISSUE TITLE
Org Bullets

### ISSUE THREAD

**Issue by ashincoder** [kristijanhusak/orgmode.nvim#38]
**Does this feature exist in Emacs orgmode?**
No. But through a mode called orgmode-bullets

**If answer to first question is "Yes", please provide the link to the orgmode manual or any documentation related to the feature**

https://github.com/sabof/org-bullets

**If answer to first question is "No", elaborate on how this feature is valuable and what problem does it solve.**

It can be good for aesthetics

**Comment by kristijanhusak** [comment]
You can use this: https://github.com/akinsho/org-bullets.nvim

I'll add it to README.

**Comment by ashincoder** [comment]
Great

**Comment by ashincoder** [comment]
I think this plugin need some fixed. It's acting weirdly. When I remove one asterisk the whole title gets deleted.

**Comment by akinsho** [comment]
@ashincoder it's still in an experimental state whilst I figure out what the best way to keep the buffer updated is. Will work on some update issues when next I get some time. It shouldn't be deleting whole titles though it only conceals text, it doesn't remove buffer content

**Comment by kristijanhusak** [comment]
@akinsho when you think it's ready let me know to add it to readme, or make a PR. I forgot to add it first time.

**Comment by ashincoder** [comment]
Great @akinsho. :smile:

**Comment by ashincoder** [comment]
> @ashincoder it's still in an experimental state whilst I figure out what the best way to keep the buffer updated is. Will work on some update issues when next I get some time. It shouldn't be deleting whole titles though it only conceals text, it doesn't remove buffer content

Sadly it does actually don't know what it is though

**Comment by akinsho** [comment]
@ashincoder you're saying removes the text from the buffer just to be clear, are you sure you just can't *see* the text? There isn't any code that actually *removes* text at all. The plugin doesn't write to the buffer at all.

**Comment by akinsho** [comment]
Thanks @kristijanhusak, I just need to refactor how updates are handled since that's currently buggy. I went with `nvim_buf_attach` but seems that api is unstable. Will be doing a refactor in the next few days and will report back after I've pushed those changes.

**Comment by ashincoder** [comment]
It is like a weird bug

**Comment by ashincoder** [comment]
Haven't tested recently @akinsho it was like 1 month ago
