### ISSUE TITLE
Table of Contents using :toc:

### ISSUE THREAD

**Issue by ashincoder** [kristijanhusak/orgmode.nvim#39]
**Does this feature exist in Emacs orgmode?**
Yes.

**If answer to first question is "Yes", please provide the link to the orgmode manual or any documentation related to the feature**

https://orgmode.org/guide/Table-of-Contents.html

**Comment by kristijanhusak** [comment]
This setting is for exporting. As far as I know there's no way to generate TOC as part of org file.

I'm working on export feature in another branch, and this option should work because export is done via emacs.

**Comment by kristijanhusak** [comment]
Exporting is not merged into master. From my tests, setting `#+OPTIONS` properly works.

To do export, check https://github.com/kristijanhusak/orgmode.nvim/blob/master/DOCS.md#org_export
