### ISSUE TITLE
Default org template being used when trying to capture

### ISSUE THREAD

**Issue by akinsho** [kristijanhusak/orgmode.nvim#4]
**Describe the bug**

Hi 👋🏾 , thanks for working on this plugin. I'd been using `dotoo` for a bit but hitting different issues. I really love the effort and care you've put into this 💯 .

One issue I've hit since moving over is that when I try to capture a new todo as far as I can see there should be a default template, but that doesn't seem to appear when I use `<leader>oc` then hit `T`

Instead I enter an empty tmp buffer without any default text. The docs mention
```
	org_agenda_templates = { t = { description = "Task", template = "* TODO %?\n %u" } },
```
but that doesn't seem to be applied by default and adding that in to my config doesn't seem to work either.

**To Reproduce**
### Minimal init.lua
```lua
vim.cmd("packadd! orgmode.nvim")

require("orgmode").setup({
	org_agenda_files = { "~/Dropbox/org/*", "~/local-org/**/*" },
	org_default_notes_file = "~/Dropbox/org/refile.org",

})
```
1. Open `nvim -u ~/minimal.lua --noplugin`
2. Hit `\oc` then `T`
3. Enter into empty temp buffer without a template

**Expected behavior**

The template should be present and ready to be filled in like the landing page GIFs

**Emacs functionality**
If this functionality exists in Emacs Orgmode, explain how it works there.

**Screenshots**
<img width="1033" alt="Screen Shot 2021-06-28 at 11 01 47" src="https://user-images.githubusercontent.com/22454918/123618571-3d997980-d800-11eb-9fe7-bcb92307fb5b.png">

**System information:**
 - OS: macOS Big Sur & Linux Ubuntu 20.04
 - Neovim version/commit: NVIM v0.5.0-dev+nightly-818-g5aaa1a1c04

**Additional context**

**Comment by kristijanhusak** [comment]
Hi,

folding caused the issue, because `search()` doesn't jump to a match if code is folded. It works for me because i have `set nofoldenable` in my config. Let me know if it works now.

Thanks for the minimal init, it really helped. It would be much harder without it.

**Comment by akinsho** [comment]
Awesome that fixed it 🚀 , thanks for the quick response.
