### ISSUE TITLE
Strikethrough syntax isn't supported

### ISSUE THREAD

**Issue by akinsho** [kristijanhusak/orgmode.nvim#42]
**Describe the bug**
Org mode supports strike through text by surrounding the text with `+` symbols
e.g. `+cancelled+` should appear as being struck through.

**To Reproduce**
1. Go to  and org file
2. type `+test+`
3. The text is not highlighted as strikethrough

**Expected behavior**
Text should appear as strikethrough which neovim supports using the `gui=strikethrough` argument to the highlight command.

**Emacs functionality**
Yes

**Screenshots**
Can't find any for the time being, but will paste some examples when I find them.

**Comment by kristijanhusak** [comment]
I didn't add it because I wasn't able to make it work with Kitty. I assume some GUIs supports it, but I haven't tried.
Do you know any terminal that supports it?

**Comment by kristijanhusak** [comment]
I added it. Not sure why it didn't work for me initially.

**Comment by akinsho** [comment]
<img width="519" alt="Screen Shot 2021-07-13 at 14 57 03" src="https://user-images.githubusercontent.com/22454918/125464689-6f9156aa-f549-4431-bcbd-cfcc7b7557fd.png">

`String         xxx gui=strikethrough guifg=#98be65`

Was just going to say about it working 😄 but you fixed it before I finished the post 😆

**Comment by kristijanhusak** [comment]
Yeah it works, not sure why it didn't work initially when I tried to add it.

**Comment by akinsho** [comment]
Hmm I don't think that works 🤔 just tried it in an org file and it doesn't show up. Maybe the `+` conflicts with another syntax group? does it work on your end?

**Comment by kristijanhusak** [comment]
Looks like it's working only in list item context:

![screenshot](https://i.imgur.com/bRsKNXu.png)

I'll take a look.

**Comment by kristijanhusak** [comment]
Pushed a fix. Should be working now.

**Comment by akinsho** [comment]
Yep can confirm that now works 👍🏾
