### ISSUE TITLE
Option to load default org-files

### ISSUE THREAD

**Issue by rgnkn** [kristijanhusak/orgmode.nvim#44]
**Does this feature exist in Emacs orgmode?**
N/A

Hello,

I'd like to ask if it would be possible - or maybe it is, but I couldn't find - to preload a set of defined org-files so that a simple <leader>oa would list those entries without opening those files manually.

Thx

**Comment by kristijanhusak** [comment]
If you mean to browse all files that are set as agenda files, you can do that simply with FZF for example:

```
:FZF ~/my/org/path
```

**Comment by rgnkn** [comment]
Not exactly.

I mean if I open vim for example without opening any files "<leader>oa", "a" shows an empty list. I need to open the according org-files (":e <path-to-org>") in order to see the details.

Again, if you don't like the idea, just close this issue and I'm going to implement it my end.

Thx.

**Comment by kristijanhusak** [comment]
If you did the setup properly, files should be loaded.
What plugin manager do you use, and how do you setup orgmode?

**Comment by rgnkn** [comment]
Packer like this:

`use("kristijanhusak/orgmode.nvim")`

orgmode is setup like this:

```
require("orgmode").setup({
	org_agenda_files = "~/orggmode/*",
	org_default_notes_file = "~/orgmode/default.org",
	org_todo_keywords = { "TODO", "BIRTHDAY", "|", "DONE" },
	org_archive_location = "~/orggmode/.archive.org",
	org_agenda_templates = {
		d = {
			description = "default (todo)",
			template = "* TODO %?\n %t",
			target = "~/orgmode/default.org",
		},
		b = {
			description = "Birthday",
			template = "* BIRTHDAY %?\n <%<%Y-%m-%d .+1y>>",
			target = "~/orgmode/birthday.org",
		},
		w = {
			description = "Work (todo)",
			template = "* TODO %?\n %t",
			target = "~/orgmode/work.org",
		},
	},
})
```

I'd like to have the 3 files: `work.org`, `birthday.org` and `default.org` always be preloaded. But they aren't.

**Comment by kristijanhusak** [comment]
Seems like you have typo in `org_agenda_files`. It should be `~/orgmode/*`, not `~/orggmode/*` (double g).

**Comment by rgnkn** [comment]
Oh, I feel so bad!

Thx and closed.
