### ISSUE TITLE
Agenda as a calendar view

### ISSUE THREAD

**Issue by rgnkn** [kristijanhusak/orgmode.nvim#45]
**Does this feature exist in Emacs orgmode?**
N/A

Hi,

Would it be possible to switch the view after <leader>oa that the "Agenda for current week or day" could be consulted as a "calendar view" instead of a long list.

I hope you get what I mean.

**Comment by kristijanhusak** [comment]
Sorry, I don't know what you mean.
If it doesn't exist in the emacs ormgode I don't plan to add it.
It can be always built as an additional plugin.

**Comment by rgnkn** [comment]
Sorry, I don't know the emacs version - I'm a pure vi-elvis-vim-nvim user for over 30 years.

I mean something like the view that you get if you type "cid" on a date. It would be IMHO better to get an overview and to navigate in time.

You can close this request if you don't plan to incorporate this, then I'll implement it my end.

thx

**Comment by kristijanhusak** [comment]
When you open up agenda with `<leader>oa`, you can jump to specific date via calendar by pressing `J`.

**Comment by rgnkn** [comment]
Ah, that's it!

Nearly:
Is there a way to indicate in the calendar view that there is a task on that day?

**Comment by kristijanhusak** [comment]
No, that's not possible. Calendar view is only for picking a date, it doesn't know about any data outside of it.

**Comment by rgnkn** [comment]
thx and closed
