### ISSUE TITLE
Option to switch to no-indent mode

### ISSUE THREAD

**Issue by jghauser** [kristijanhusak/orgmode.nvim#46]
**Does this feature exist in Emacs orgmode?**
Yes

**If answer to first question is "Yes", please provide the link to the orgmode manual or any documentation related to the feature**

https://orgmode.org/manual/Org-Indent-Mode.html

**Additional context**

In emacs orgmode indent is done (if I understand correctly, I have never used it) by adding virtual white space. That is, the plain text file does not contain any indent whitespace, but these are shown in emacs orgmode. This isn't (yet) possible in neovim though it is a goal for 0.6. In any case, orgmode.nvim currently simply adds real whitespace to the files. This leads to problems in some cases:

1. tab to indent e.g. list items only works if the indent is an even number of whitespace. Thus if I'm in a subheading (`**`) then tab will increase indent only by one instead of two whitespaces.
2. Compatability with emacs tools. In particular I have in mind the android orgzly application, which expects no (real) indent in the files.

I would like an option that toggles indent mode. As far as I can tell, in emacs orgmode indent is turned off by default.

**Comment by kristijanhusak** [comment]
As you said, this cannot be currently done in Neovim. Hopefully they will add support for it at some point. Only way that i can think of is to modify the content each time when indent is enabled/disabled, but that seems like a too hacky solution.

**Comment by jghauser** [comment]
I guess what I was hoping for is a mode where no indents are created. Currently, if I press enter after adding a new heading it will automatically indent the next line. Or is this happening because of some setting I have enabled somewhere and forgot?

**Comment by kristijanhusak** [comment]
No, there's no setting for that, but it can be easily added.

**Comment by jghauser** [comment]
That would be excellent! I'd like to keep my files unindented as having things work properly on my phone is pretty important to me. Looking forward to virtual space being added to neovim in the future so that I can have the best of both worlds :).

**Comment by kristijanhusak** [comment]
I added the option. See https://github.com/kristijanhusak/orgmode.nvim/blob/master/DOCS.md#org_indent_mode.

Currently it supports only configuration level. Document level (via `#STARTUP` option) is not yet supported.

**Comment by jghauser** [comment]
Excellent, it works! Thanks a ton! I'll come again for the virtual space once neovim implements it ;)

**Comment by jghauser** [comment]
Found an instance where things are still indented. When I mark a repeating task as done, the :PROPERTIES: section that gets added is indented but shouldn't be.

**Comment by kristijanhusak** [comment]
Good catch. Should be fixed now.

**Comment by jghauser** [comment]
Noticed one more thing. Would it be possible for the noindent option to still create new list items at the same level as the previous item? Currently, with noindent on, pressing enter will always bring me to the beginning of the line. This is perfect for headings, but a little inconvenient for list items.

Even with noindent on, I think the following behaviour would make sense:
```
- some list item
  - indented list item<cr>
  |
```
rather than:
```
- some list item
  - indented list item<cr>
|
```

**Comment by kristijanhusak** [comment]
Yeah, that's how emacs orgmode works. Fixed it.

**Comment by jghauser** [comment]
almost! but now it indents too much :D. rather than indenting to the same level as the above line, it indents as would be appropriate for a sub-item. 

currently:

```
- some list item
  - indented list item<cr>
    |
```

what i think would be better:

```
- some list item
  - indented list item<cr>
  |
```

Or is this really the emacs default?

**Comment by kristijanhusak** [comment]
I'm replicating how emacs orgmode is behaving. You can insert new list item with `<leader><CR>`.

**Comment by jghauser** [comment]
Ah, that makes sense and is consistent with the functioning elsewhere. Although I have to say I now regret picking <space> for <leader>. But that's my bad. Maybe it's time to retrain my brain a little!

In any case, thanks a ton for looking into this so quickly! orgmode.nvim is getting better by the day!

**Comment by jghauser** [comment]
Just found another issue! Promoting and demoting headlines still adds/removes indent even if indent-mode is turned off.

**Comment by kristijanhusak** [comment]
Should be fixed now.

**Comment by IllustratedMan-code** [comment]
Neovim 0.6 was just released, so the virtual indentation should now be possible right?

**Comment by kristijanhusak** [comment]
I think they didn't add support for it yet. 0.6 came out fairly fast, so I think support for virtual indentation will be added in some of the future releases.
