### ISSUE TITLE
Promoting/Demoting opens fold.

### ISSUE THREAD

**Issue by Maltimore** [kristijanhusak/orgmode.nvim#50]
**Describe the bug**
Promoting/Demoting opens fold.

**To Reproduce**
1. Go to a closed fold headline
2. Promote/demote subtree with ">s" in normal mode
3. headline will get demoted but the fold will be opened.

**Expected behavior**
Fold stays closed

 - OS: Linux Ubuntu
 - Neovim version/commit: most recent as of 2021-07-16

**Comment by kristijanhusak** [comment]
Folds are a bit tricky in neovim because they automatically open once you modify the content. I pushed a fix as an attempt to fix it. Can you pull latest master and give it a try?

**Comment by Maltimore** [comment]
Looks good! Thanks a lot.

It actually sounds like one should have a discussion on the neovim issue tracker whether it is desired that folds open automatically when something changes?!

There is still a small problem with promoting: if you promote a subtree where the next (sub-)level is currently expanded but the level after that is still collapsed, it will expand everything. However if the subtree is completely collapsed, it works as intended. I don't consider this particularly problematic though (and anyways it should probably be fixed on neovims side), so I'll close.
