### ISSUE TITLE
Cancelling capture freezes neovim if UltiSnips tabstops are left untouched before cancellation

### ISSUE THREAD

**Issue by physicophilic** [kristijanhusak/orgmode.nvim#51]
Thank you for your plugin Kristijan. It is great.

 I found this issue so I'm reporting.

**Describe the bug**
In org capture, `<leader>ok` is used to cancel capture. Usually the cancellation is snappy, but if one uses UltiSnips snippets before cancelling containing tabstops, neovim freezes for a few seconds (~5) if the tabstops aren't touched.

**To Reproduce**
Install ultisnips and add following snippet to `/path-to-Ultisnips/org.snippets`

```snippet
snippet test "Test" iA
Event  $1
endsnippet
```
As soon as you trigger `test`,  escape and press `<leader>ok` or `:q!`, and neovim should freeze.
This can be avoided if the tabstops are touched. For example, `Event 22` should quit fine.

This doesn't happen in other `org` buffers, nor in any other filetypes.

**Expected behavior**
The cancellation behaviour should be snappy as always - it should just simply drop whatever's in the buffer.

**System information:**
 - OS: Linux
 - Neovim version/commit: `nvim-0.6 dev`

**Comment by kristijanhusak** [comment]
I'm not able to reproduce this:
![capture](https://user-images.githubusercontent.com/1782860/126048057-b3be00ae-32df-4576-8e39-9512b9ed1cc8.gif)

`<leader>ok` just does `:bwipeout!` . Can you try and see what happens when you do `:bwipeout!` instead of `<leader>ok` ?

**Comment by physicophilic** [comment]
I'll add a GIF later but yes, even `:bwipeout!` freezes it for a while.

**Comment by physicophilic** [comment]
It seems this is related to `neovim` core. I updated mine, and the behaviour has changed. It doesn't freeze for noticeable time. Thanks for your vigilance.
