### ISSUE TITLE
Code block highlighting only activates after reloading file

### ISSUE THREAD

**Issue by jacksonludwig** [kristijanhusak/orgmode.nvim#55]
**Describe the bug**
When using code-block functionality, I noticed I have to reopen the file for syntax highlighting to work.

**To Reproduce**
1. Open org file
2. Write `#+BEGIN_SRC <lang>`
3. Write a line of code below it
4. Make another new line and write `#+END_SRC <lang>`
5. Observe highlighting is missing
6. run `:e <filename>`
7. Observe highlighting is working

**Expected behavior**
Code in code block to be highlighted before reloading the file

**System information:**
 - OS: Linux
 - Neovim version/commit: https://github.com/neovim/neovim/commit/d8f5f4d09078e7d52d1abd13418133da10b2cc27

**Comment by kristijanhusak** [comment]
This should be fixed now. Block should be highlighted as soon as file is written.

**Comment by jacksonludwig** [comment]
@kristijanhusak To clarify, is there currently any way to get the highlighting to update without having to save/write the file first? It's not a big deal but just wondering.

Thanks for your efforts.
