### ISSUE TITLE
Dashboard cannot make changes

### ISSUE THREAD

**Issue by danielnehrig** [kristijanhusak/orgmode.nvim#56]
**Describe the bug**
When in the Dashboard buffer (glepnir/dashboard.nvim)
when you try to open up agenda or capture
you'll get
```
E21: Cannot make changes, 'modifiable' is off
```

**To Reproduce**
1. Install the Dashboard plugin
2. Make sure nvm opens up with the dashboard buffer
3. on that buffer open up orgmode capture / agenda

**Expected behavior**
orgmode plugin opens up agenda and capture

**System information:**
 - OS: arch
 - Neovim version/commit: NVIM v0.6.0-dev+49-gc36df20ae

**Comment by kristijanhusak** [comment]
I'm not able to reproduce it:

![dashboard_issue](https://user-images.githubusercontent.com/1782860/126787092-cff0dada-cf97-4273-a5ae-4ab59caa019b.gif)

Could you try with minimal init that has only orgmode and dashboard?

**Comment by danielnehrig** [comment]
issue resolved im stupid
i lazyloaded on insertenter compe and orgmode after compe is loaded
therefor since insertenter event never triggered it wasn't able to trigger orgmode

sorry for wasting your time
