### ISSUE TITLE
Adding a new headline makes it get folded in the wrong level

### ISSUE THREAD

**Issue by Maltimore** [kristijanhusak/orgmode.nvim#61]
### Describe the bug

Adding a new headline makes it get folded in the wrong level

### Steps to reproduce

1. Open a file with the following content:
```
* headline 1
some content
```
2. Add a headline such that the buffer looks like this:
```
* headline 1
some content
* headline 2
```
3. Go to the line with headline 1 and close the fold (with `zc` in normal mode)
4. You can observe that there's now just 1 fold, and headline 2 is hidden within that fold.

### Expected behavior

Headline 1 including `some content` should get folded. Headline 2 should be separate from this (i. e. not vanish in the fold) because it is on the same level as headline 1.
### OS / Distro

Ubuntu 20.04, alacritty

### Neovim version/commit

latest HEAD on 2021-08-04

### Additional context
If you open a file that already contains all the content (i.e. both headlines), the folding works as expected.

**Comment by kristijanhusak** [comment]
This is due to `foldexpr` needing to recalculate the folds. You can read more about it here https://neovim.io/doc/user/fold.html#zx.

Using `Tab` to toggle folds instead of `zc` should make it work fine.

**Comment by Maltimore** [comment]
I see, that's an easy enough workaround, thank you!
If I press tab on the lowest headline to fold it, the cursor jumps one line up. Not really a relevant issue though.
