### ISSUE TITLE
Change todo state in org agenda

### ISSUE THREAD

**Issue by romariorobby** [kristijanhusak/orgmode.nvim#62]
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

[org-agenda-todo](https://orgmode.org/manual/Agenda-Commands.html)

**Comment by kristijanhusak** [comment]
This is now added. See this section in readme https://github.com/kristijanhusak/orgmode.nvim/blob/master/DOCS.md#org_agenda_todo.

Just press `t` on item in any agenda view (agenda, todos, search, etc.)

**Comment by romariorobby** [comment]
Oh that's so fast. Gonna try now!

**Comment by romariorobby** [comment]
it worked . but i have to cycle to every keywords. its kind of annoying when you have more than two TODO keywords. I think it will be great if implement a small popup like on Emacs. like this:
I believe vim-dotoo also have this too.
![Screen Shot 2021-08-05 at 6 06 01 AM](https://user-images.githubusercontent.com/40323094/128266611-b9b658c1-1cd8-4e3d-9475-96025e2d08e9.png)

**Comment by kristijanhusak** [comment]
Do you know what's the shortcut to trigger this view in Emacs? `org-agenda-todo` specifically just cycles todo keyword, so I replicated the functionality. I'm ok with adding this as long as it's possible to be done in Emacs' org.

**Comment by romariorobby** [comment]
https://orgmode.org/manual/Fast-access-to-TODO-states.html#Fast-access-to-TODO-states. 
In Doom emacs(I use vim emulation mode) so its bind to `SPC m t`.

![Screen Shot 2021-08-06 at 8 48 08 AM](https://user-images.githubusercontent.com/40323094/128443575-22e2eb26-763a-4f79-b8de-063860fe7f27.png)

**Comment by kristijanhusak** [comment]
Thanks, I wasn't aware of this feature. It is generally a separate feature, so I'll handle that in a different commit.

**Comment by kristijanhusak** [comment]
@romariorobby I added support for fast access to TODO states. You can now provide fast access keys for todo keywords and `cit` will open up a prompt. See this section in docs for more info https://github.com/kristijanhusak/orgmode.nvim/blob/master/DOCS.md#org_todo_keywords.

Please let me know how it works.

**Comment by romariorobby** [comment]
Ah yeah, it worked perfectly. Thanks for adding this feature!
