### ISSUE TITLE
Implement insert schedule/deadline for a task

### ISSUE THREAD

**Issue by mortezadadgar** [kristijanhusak/orgmode.nvim#65]
### Does this feature exist in Emacs orgmode core?

N/A

### Additional context

In doom emacs(idk about vanilla) a task can be scheduled with SPC m d s keys or SPC m d d for deadlines

**Comment by kristijanhusak** [comment]
It needs to be added. Related manual documentation: https://orgmode.org/manual/Inserting-deadline_002fschedule.html

**Comment by mortezadadgar** [comment]
> It needs to be added. Related manual documentation: [orgmode.org/manual/Inserting-deadline_002fschedule.html](https://orgmode.org/manual/Inserting-deadline_002fschedule.html)

Are you willing to implement this feature

**Comment by kristijanhusak** [comment]
Yeah, I'll add it.

**Comment by kristijanhusak** [comment]
This is added. 
Adding deadline date: https://github.com/kristijanhusak/orgmode.nvim/blob/master/DOCS.md#org_deadline
Adding schedule date: https://github.com/kristijanhusak/orgmode.nvim/blob/master/DOCS.md#org_schedule

Let me know if it works ok.

**Comment by mortezadadgar** [comment]
@kristijanhusak yeah works fine
btw what's the default color fallback for todo keyworks highlight, I have tried to change but it didn't work [related commit](https://github.com/mortezadadgar/onedark-nvim/commit/f7acb5ca3d97490cbac28cd614fde5711f7bbf60)

**Comment by kristijanhusak** [comment]
Use https://github.com/kristijanhusak/orgmode.nvim/blob/master/DOCS.md#org_todo_keyword_faces to change colors of todo keywords, or override `OrgTODO` and `OrgDONE` hl groups, not the built in ones.

Changing hl of the whole line like that is tricky, it requires too much hacking around syntax matching.

**Comment by mortezadadgar** [comment]
@kristijanhusak thanks! and there's a small typo with the configuration example you provided `TODO -` should be `TODO =`

**Comment by kristijanhusak** [comment]
Thanks, fixed it.
