### ISSUE TITLE
motions to cit and ciT

### ISSUE THREAD

**Issue by lbiaggi** [kristijanhusak/orgmode.nvim#69]
### Does this feature exist in Emacs orgmode core?

N/A

### Additional context

I think your work is wonderful, I just miss vim motions to move states.

e.g.:
```
STATES -> { 'TODO', 'NEXT', 'DOING', '|', 'DELEGATED', 'DONE', 'ARCHIVED', 'TRANSFERED'}
			  				   /\ I am here, but i want to ARCHIVED, so i would type 3cit instead of cit 3 times.

```
Is it plausible?

**Comment by kristijanhusak** [comment]
If you are jumping more than one step ahead, I suggest checking out the "fast access" feature. More in this section of readme https://github.com/kristijanhusak/orgmode.nvim/blob/master/DOCS.md#org_todo_keywords

**Comment by lbiaggi** [comment]
I read it, but it feels like cheating vim motions, I will give it a try.

**Comment by kristijanhusak** [comment]
these `cit` mappings are not really a motion mappings, since there is no visual/yank/delete representation of it. It's just a regular normal mode mapping. Count could be added though, so I'll check it out when I get some time.

**Comment by lbiaggi** [comment]
Okay, thanks I'm new to orgmode.
