### ISSUE TITLE
Support mapping in other mode?

### ISSUE THREAD

**Issue by romariorobby** [kristijanhusak/orgmode.nvim#70]
### Does this feature exist in Emacs orgmode core?

N/A

### Additional context

Is there a way to bind in insert mode? I'd like to bind `do_demote` with `TAB` and `do_promote` `S-TAB` . I know in documentation says only works in normal mode.

**Comment by romariorobby** [comment]
Yes, that how i solved this too with recursive mapping. Thank you!

**Comment by darg2012** [comment]
Hi, I'm trying to achieve the same behavior with the meta_return mapping, at the end of my lua/after/org.lua file I have:
`vim.keymap.set('i', '<Space><CR>', '<C-o><leader><CR>')`
but it does not work as keymap despite the {rhs} working as expected if typed manually.

I tried also this mapping:
`vim.keymap.set('i', '<<Tab>', '<C-o><leader>oi.')`
but I only get `oi.` inserted in my buffer.

Could anyone guide me on applying such keymaps? Thanks.
