### ISSUE TITLE
Start with all folds exploded

### ISSUE THREAD

**Issue by mcepl** [kristijanhusak/orgmode.nvim#74]
### Does this feature exist in Emacs orgmode core?

N/A

### Orgmode link

Probably this is just a missing piece of documentation, but how can I make orgmode to start with all levels expanded. I tried to set `vim.opt.foldlevelstart=99` in `~/.vim/plugin/orgmode-settings.lua` (which is my configuration of orgmode), but vim still opened `.org` file with folds closed. Only modeline hardcoding `foldlevel` helped, but it is not very good strategy.

**Comment by kristijanhusak** [comment]
I assume you have `foldenable` set to true by default, so you need to disable it in org filetype if you don't want it:

```lua
vim.cmd[[autocmd FileType org setlocal nofoldenable]]
```

**Comment by mcepl** [comment]
THanks, that works.
