### ISSUE TITLE
[tree-sitter] Folding does not work

### ISSUE THREAD

**Issue by Happy-Dude** [kristijanhusak/orgmode.nvim#75]
### Are you using "tree-sitter" branch?

Yes

### Describe the bug

Folding org-mode files not functional (at the moment?)

### Steps to reproduce

Sample file:

```org
* Unfiled
** DONE woops, wrong file
CLOSED: [2018-06-12 Tue 21:05]
```

1. Open file above
2. Use shortcut `<Tab>` or `<Shift-Tab>`

### Expected behavior

* Using <Tab> at top-level bullet should collapse/expand tree and elements below

### Emacs functionality

* Same(?) behavior from emacs org-mode and master branch orgmode.nvim: elements should be collapsible/expandable

### Screenshots and recordings

Will provide screenshot/gif if requested.

### OS / Distro

macOS 10.15.7

### Neovim version/commit

NVIM v0.6.0-dev+212-g5f8518b3f (via Homebrew)

### Additional context

* Current dotfiles/nvim config settings: https://github.com/Happy-Dude/dotfiles/commit/8804a95604463edf313b750a811d4961c3c82319
* Installed parser via `:TSInstallFromGrammar org`

**Comment by kristijanhusak** [comment]
I'm not able to reproduce this. Here's a gif:
![folding](https://user-images.githubusercontent.com/1782860/132029054-37598bdd-4860-4086-a199-f5ecb4032748.gif)

Are you sure your `<TAB>` key is properly bind?

What you get as output for this command:
```
:map <TAB>
```

**Comment by Happy-Dude** [comment]
Thanks for pointing out that this was a problem with my own config;

I was setting buffer-local foldmethod/foldexpr via https://github.com/Happy-Dude/dotfiles/blob/fd8c052f7f04d47986bed5f23d98114701e0588c/vim/.vim/lua/treesitter.lua#L89-L103, and things work once I replaced that snipped of code with the following: https://github.com/nvim-treesitter/nvim-treesitter/issues/475#issuecomment-748532035

Closing as this was an issue with my personal config 👍

**Comment by kristijanhusak** [comment]
I'll add this to readme. I didn't think about treesitter foldexpr at all, since I'm not using it. People can easily run into this problem with both foldexpr and indentexpr.
