### ISSUE TITLE
Toggling fold while on last (empty) line of it

### ISSUE THREAD

**Issue by jghauser** [kristijanhusak/orgmode.nvim#76]
### Are you using "tree-sitter" branch?

No

### Describe the bug

Consider the following text:

```
* Some entry
- Some
- text
|
* Another entry
```

If my cursor is at the position `I`, then I would expect `<tab>` to toggle the fold. It doesn't do that (it does nothing).

### Steps to reproduce

1. Open a .org file
2. Go to the last (empty) line of a fold
3. Try to toggle fold with `<tab>`

### Expected behavior

Folds should toggle.

### Emacs functionality

I don't know.

### OS / Distro

Arch Linux

### Neovim version/commit

NVIM v0.6.0-dev+182-ga373ca1d8

**Comment by kristijanhusak** [comment]
Should be fixed now. Please give it a test.

**Comment by jghauser** [comment]
Works! Thanks a lot :)
