### ISSUE TITLE
Repeating todos when using fast access kewords don't reactivate

### ISSUE THREAD

**Issue by jghauser** [kristijanhusak/orgmode.nvim#77]
### Are you using "tree-sitter" branch?

No

### Describe the bug

When using fast access keywords and selecting `DONE` on a repeating todo, the entry is set to `DONE`. When not using fast access and setting it to `DONE`, the due date is advanced as necessary and the entry remains as `TODO`. (This happens both when in the agenda and when in a .org file.)

### Steps to reproduce

1. Enable fast access
2. Create a repeating TODO
2. Set the TODO to `DONE`

### Expected behavior

The entry should not be set to `DONE`, but the due date advanced as necessary and the state should remain `TODO`. That is, fast access behaviour should be the same as normal behaviour.

### Emacs functionality

I don't know.

### OS / Distro

Arch Linux

### Neovim version/commit

NVIM v0.6.0-dev+182-ga373ca1d8

**Comment by kristijanhusak** [comment]
It opened prompt twice by mistake. Should be fixed now.

**Comment by jghauser** [comment]
Perfect, thanks for the super quick fix! It works great :)
