### ISSUE TITLE
New entries in numbered lists aren't automatically created with <cr><leader>

### ISSUE THREAD

**Issue by jghauser** [kristijanhusak/orgmode.nvim#78]
### Are you using "tree-sitter" branch?

No

### Describe the bug

When pressing `<leader><cr>` (`org_meta_return`) in a numbered list, the list isn't continued. I think -- just like unnumbered lists -- the list should be continued. 

### Steps to reproduce

1. Open a .org file
2. Create a numbered list `1. Some text`
3. Press <leader><cr>

### Expected behavior

The numbered list should be continued. So if there is a `1. Some text` a new line beginning with `2. ` should be created. I'm not sure what would be the proper behaviour in case of pressing <leader><cr> in the middle of a numbered list.

### Emacs functionality

I'm not sure.

### OS / Distro

Arch Linux

### Neovim version/commit

NVIM v0.6.0-dev+182-ga373ca1d8

**Comment by kristijanhusak** [comment]
This should be fixed now (on master branch). Please give it a try.

**Comment by jghauser** [comment]
And this also works! :)
