### ISSUE TITLE
Document date time abbreviations

### ISSUE THREAD

**Issue by akinsho** [kristijanhusak/orgmode.nvim#8]
This isn't really a bug per se but there was no other fitting issue type.

I saw in the GIF regarding autocompletion that `:now:` was being autocompleted to
a date time and didn't realise that this wasn't coming from `compe` and was confused as to why it wasn't working.

I eventually realised that it was an `iabbrev` command and that it only expands after you enter a space i.e. `:now:<space>` will expand but `:now:` won't. Which isn't necessarily an issue, I just wanted to suggest that this be documented somewhere since from the GIF it's not clear how this works or what is available e.g. is just now? can other words work?

**Comment by kristijanhusak** [comment]
I'll set up more issue types, thanks.

Yeah, I forgot to add those. It's only `:today:` and `:now:`, where :today: is today's date, and now is today's date with current time.

I'll add those to readme and docs.
