### ISSUE TITLE
Adding a time stamp for todo keywords other than DONE

### ISSUE THREAD

**Issue by gerazov** [kristijanhusak/orgmode.nvim#84]
### Does this feature exist in Emacs orgmode core?

N/A

### Feature value

Awesome plugin :sunglasses: !

It would be nice to be able to keep track of time spent doing a task. I know that it's in your pipeline, but a proxy would be really helpful.

What I have in mind is the possibility to add a STARTED timestamp, in a similar way that the CLOSED timestamp is added. And tie it to a todo keyword, e.g. TODO -> DOING -> DONE. I'm currently doing this manually :sweat_smile:

**Comment by kristijanhusak** [comment]
Anything outside `DEADLINE`, `SCHEDULED` and `CLOSED` are outside of the orgmode syntax, and I don't plan to support it. Logging time will be added at some point, and most likely on tree-sitter branch.

**Comment by gerazov** [comment]
Ok #88 kinda solves it, if it could also stamp the current time ...

**Comment by kristijanhusak** [comment]
@gerazov if you really want to set up something for yourself until time tracking is added, I suggest to just write few lines of code to achieve it.
To get current time you can do two things:

* type `:now:` and press space, it should print the current time (it's abbreviation)
* Write some function that will add a current date and time to the document, and you can get it like this:
```vim
" Note: this is vimscript
" active_flag is boolean, that determines if `<>` or `[]` is used. when true, `<>` is used
let date = luaeval("require('orgmode.objects.date').now():to_wrapped_string(active_flag)")
```

**Comment by gerazov** [comment]
Ok thanks!

**Comment by kristijanhusak** [comment]
@gerazov Clocking support is now added to the [tree-sitter](https://github.com/kristijanhusak/orgmode.nvim/tree/tree-sitter) branch.

You can read about it in the [docs](https://github.com/kristijanhusak/orgmode.nvim/blob/tree-sitter/DOCS.md#clocking).

I would appreciate your feedback on this.
