### ISSUE TITLE
Mapping to insert plain timestamps

### ISSUE THREAD

**Issue by ourigen** [kristijanhusak/orgmode.nvim#88]
### Does this feature exist in Emacs orgmode core?

Yes

### Orgmode link

https://orgmode.org/manual/Creating-Timestamps.html

### Additional context

I think extending #65 to include mappings for inserting plain and inactive timestamps (without `SCHEDULED:` or `DEADLINE:`) would bring feature parity with time-stamping in org-mode. Default mappings could be `<Leader>oi.` for plain timestamp and `<Leader>oi!` for inactive timestamp similar to Emacs' bindings

**Comment by gerazov** [comment]
:+1:  this would solve #84 - I've not used Emacs so I'm not sure what is the org way to keep track of time spent on tasks :slightly_smiling_face:

**Comment by kristijanhusak** [comment]
I added it, it's mapped to `<Leader>oi.` and `<Leader>oi!`. Let me know if there are any issues with it.

**Comment by ourigen** [comment]
Thanks for the quick work on this! One issue is that the timestamp is inserted at cursor position so it breaks up the text i.e. 
`* TODO My task` -> `* TODO My tas<2021-09-17>k`
Could it be changed so that the timestamp is inserted on a newline?

**Comment by kristijanhusak** [comment]
Emacs does the same thing:
![insert-timestamp](https://user-images.githubusercontent.com/1782860/133852361-47508bd8-f8ac-4f9c-abc8-c2b9dd78f64b.gif)

So if you have this happening often I suggest to create a custom mapping that will first append a new line below and then trigger the org mapping.

**Comment by ourigen** [comment]
The problem though is that Vim bindings require that you enter normal mode before you can use the keybinding to insert date.  When you hit escape, the cursor moves one character before where you were typing, so when you insert a date it always breaks up the last character of the line. Even if you leave an extra whitespace before exiting insert mode, inserting date will leave the trailing whitespace. Emacs (at least without Evil bindings) can be inserted inline with the same spacing.

**Comment by kristijanhusak** [comment]
I could use `a` instead of `i` when adding a date, but that would potentially cause a different kind of issues.

If you want to have a one liner, something like this work. I think it's a bit trickier because modes are switched in a single mapping

```vim
nnoremap <silent><my-keys> o<Esc>:exe "norm \<Leader>oi."<CR>
```

or this:
```vim
:nnoremap <silent><my-keys> o<Esc>:call feedkeys("\<Leader>oi.")<CR>
```

**Comment by ourigen** [comment]
The mapping is hacky but works okay. Thanks!

**Comment by gerazov** [comment]
Is it possible for this to give the current time as well? :thinking:
