### ISSUE TITLE
Reverse colors in calendar matches excess elements

### ISSUE THREAD

**Issue by ourigen** [kristijanhusak/orgmode.nvim#93]
### Are you using "tree-sitter" branch?

Yes

### Describe the bug

Just a minor bug but I noticed that the reverse color highlighting for the current day in calendar view matches other elements that's not the current day

### Steps to reproduce

I pressed`<Leader>oid` or `<Leader>ois` on a headline to get to calendar view

### Expected behavior

Only the current day should be highlighted

### Screenshots and recordings

![](https://user-images.githubusercontent.com/79729735/134068626-ce08adb4-14da-4230-8232-6c4d9848dc76.png)

Note that the ` 202` in `September 2021` is highlighted. 

(`M` is where my cursor is and `20` under the `Mon` column is the current date)

### OS / Distro

Arch Linux

### Neovim version/commit

v0.6.0-dev

**Comment by kristijanhusak** [comment]
Thanks. Should be fixed now.
