### ISSUE TITLE
incorrect cursor position with custom template.

### ISSUE THREAD

**Issue by evolify** [kristijanhusak/orgmode.nvim#94]
### Are you using "tree-sitter" branch?

No

### Describe the bug

When I use the template '* TODO %? %u', the cursor in the end of the line, not between TODO and date as expected.

### Steps to reproduce

1. set agenda template:     T = { description = 'Todo', template = '* TODO %? %u', target = '~/org/todo.org' },
2. type `leader`oc > T

### Expected behavior

Cursor between TODO and date

### OS / Distro

macOS 11.0.1

### Neovim version/commit

0.5

**Comment by kristijanhusak** [comment]
Having content after the cursor marker caused an issue. Should be fixed now.
