### ISSUE TITLE
Dates of type NONE aren't displayed in agenda

### ISSUE THREAD

**Issue by frostbytten** [kristijanhusak/orgmode.nvim#97]
### Are you using "tree-sitter" branch?

Yes

### Describe the bug

Dates with type NONE are not being displayed in the agenda. If SCHEDULED or DEADLINE, dates work correctly in the agenda.

### Steps to reproduce

1. Create new TODO with a date:
```
* TODO Something
  <2021-10-01 Fri>
```

2. Open agenda
3. Date is not appearing

### Expected behavior

The TODO should appear, if the date is in the correct window of time.

### OS / Distro

Manjaro 21.1.4 (i3)

### Neovim version/commit

NVIM 0.5.0

### Additional context

I switched back to the main branch and it was functional.

**Comment by kristijanhusak** [comment]
Should be fixed now. I didn't know "NONE" dates are returned on second line as part of "plan" node.
