### ISSUE TITLE
Brackets in links are not concealed

### ISSUE THREAD

**Issue by jbarik** [kristijanhusak/orgmode.nvim#99]
### Are you using "tree-sitter" branch?

No

### Describe the bug

![org_link_issue](https://user-images.githubusercontent.com/22386546/135705276-43aaf79b-68a9-49d3-8ba6-c11b53eff826.png)

As shown in the above message, for links the brackets are not hidden. Am I missing some setting. My minimal init.vim to reproduce the issue

init.vim
==================================

function! PackagerInit() abort    
   packadd vim-packager    
   call packager#init()    
   call packager#add('kristijanhusak/orgmode.nvim')                             
endfunction    
    
command! PackagerInstall call PackagerInit() | call packager#install()    
command! -bang PackagerUpdate call PackagerInit() | call packager#update({ 'force_hooks': '<bang>' })    
command! PackagerClean call PackagerInit() | call packager#clean()      
command! PackagerStatus call PackagerInit() | call packager#status()    
               
lua << EOF    
require('orgmode').setup({    
  org_hide_leading_stars = true                                      
})    
EOF

### Steps to reproduce

My org file contnts:
[[test]]
[[test][link to test]]

### Expected behavior

The brackets should be hidden

### Screenshots and recordings

![org_link_issue](https://user-images.githubusercontent.com/22386546/135705387-2a8e592b-77cc-40e9-a58d-817e314eea26.png)

### OS / Distro

Ubuntu 20.04.3 LTS

### Neovim version/commit

NVIM v0.5.0-dev+1372-g056c464e8

**Comment by kristijanhusak** [comment]
what's your conceallevel (`:echo &conceallevel`) while you're in the org buffer?

**Comment by jbarik** [comment]
:echo &conceallevel produces the answer 0

**Comment by kristijanhusak** [comment]
try doing `:setlocal conceallevel=2` while in org buffer and see if it works then.

**Comment by jbarik** [comment]
:setlocal conceallevel=2   didn't help

**Comment by kristijanhusak** [comment]
Ok, and what about the output of `echo &concealcursor` ?

**Comment by jbarik** [comment]
echo &concealcursor is empty

**Comment by kristijanhusak** [comment]
Ok. You need to add `set conceallevel=2` to your vimrc. If you want  to have concealing only for org, add it to autocmd:

```vim
autocmd FileType org setlocal conceallevel=2
```

**Comment by jbarik** [comment]
Thanks a lot. with conceallevel=2 the issue is solved, but I am seeing one more behaviour. the moment my cursor is on the line containing the link it gets exapnded. I would like it to be expanded when I am in insert mode - I am switching from vim-orgmode, where that was the behaviour. Can I change some setting to get my desired behaviour.

**Comment by kristijanhusak** [comment]
Yes, add also `setlocal concealcursor=nc` to the autocmd.

**Comment by jbarik** [comment]
Sorry to bother again. I see that even with conceallevel=2,  the brackets are not hidden when it is inside a heading
![Screenshot from 2021-10-02 15-19-30](https://user-images.githubusercontent.com/22386546/135711325-bb5c53a8-5102-42ea-bd1c-ce25d40e3ab4.png)

**Comment by kristijanhusak** [comment]
Links in headline are not supported because of similar issue like [this](https://github.com/kristijanhusak/orgmode.nvim/issues/67#issuecomment-902668968). You should use `tree-sitter` branch with experimental highlighting enabled if you want this.

**Comment by jbarik** [comment]
Good to know that tree-sitter branch will fix this. For now, I replaced the line 

"syntax match org_hyperlink	"\[\{2}[^][]*\(\]\[[^][]*\)\?\]\{2}" contains=org_hyperlinkBracketsLeft,org_hyperlinkURL,org_hyperlinkBracketsRight" 

in org.vim file to 

"syntax match org_hyperlink	"\[\{2}[^][]*\(\]\[[^][]*\)\?\]\{2}" contains=org_hyperlinkBracketsLeft,org_hyperlinkURL,org_hyperlinkBracketsRight containedin=OrgHeadlineLevel1,OrgHeadlineLevel2,OrgHeadlineLevel3,OrgHeadlineLevel4,OrgHeadlineLevel5"

With this I think it'll work for 5 levels of heading and I can live with that till tree-sitter branch becomes the main.

Thanks for your effort.

**Comment by sethidden** [comment]
There seems to be an issue with line wrapping if the link URL is very long
![image](https://user-images.githubusercontent.com/5359825/142275687-237aa05c-ee21-4a26-a971-f9e1944473ef.png)
![image](https://user-images.githubusercontent.com/5359825/142275713-f23fd9ab-684b-4484-b63c-5ec8af4607a5.png)

This is with `disable = {'org'}` in Treesitter as I saw the notice that concealing in TS is unsupported. Should I open a separate issue?

**Comment by kristijanhusak** [comment]
@sethidden I don't think this can be fixed. It's just how concealing works in Vim. Try doing `set conceallevel=0` and see how it really looks in the background. There is no way to control this behavior. As you said, `nowrap` should do the trick.

**Comment by sethidden** [comment]
For organization's sake - concealed text wrongly contributing to wrapping is reported upstream in neovim under https://github.com/neovim/neovim/issues/14409
